name            = Java Plugin Launcher
description     = A thin application to implement a microkernel architecture.
version         = 1.0.0

url             = https://github.com/Akazukin-Team/Java-Plugin-Launcher

vendor          = Akazukin Team
vendor-url      = https://github.com/Akazukin-Team

groupId         = org.akazukin


archiveBaseName = Launcher
mainClass       = org.akazukin.app.loader.Main
